version: '2'
services:
    elasticsearch:
        image: diabol/elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - ./elasticsearch/data:/opt/elasticsearch/data
            - ./elasticsearch/logs:/opt/elasticsearch/logs
            - ./elasticsearch/config:/opt/elasticsearch/config
    kibana:
        image: diabol/kibana
        ports:
            - "5601:5601"
        volumes:
            - ./kibana/config:/opt/kibana/config
        depends_on:
            - elasticsearch    
    logstash:
        image: diabol/logstash
        volumes:
            - ./logstash/config:/opt/logstash/config
            - ./logstash/demologs:/tmp/demologs
        depends_on:
            - elasticsearch

